# Generated by Django 4.2.26 on 2025-11-28 01:15

from django.db import migrations, models
import random
import string


class Migration(migrations.Migration):

    dependencies = [
        ('gezana_app', '0002_table_booking'),
    ]

    def generate_refs(apps, schema_editor):
        Booking = apps.get_model('gezana_app', 'Booking')
        for booking in Booking.objects.all():
            if booking.reference:
                continue
            while True:
                code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
                if not Booking.objects.filter(reference=code).exists():
                    booking.reference = code
                    booking.save(update_fields=["reference"])
                    break

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.RunPython(generate_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
