# Generated by Django 4.2.26 on 2025-12-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gezana_app', '0005_seed_default_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
